# This is a basic workflow to help you get started with Actions

name: py

on:
  schedule:
    - cron: "20 11 * * *"    #runs at 17:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            pip install numpy
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        run: |
          python ETL_pipeline.py
